// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vazqzipehewahhcqtdfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhenF6aXBlaGV3YWhoY3F0ZGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjU5ODIsImV4cCI6MjA1OTM0MTk4Mn0.6X5YZWz_yfBlX93U0C_Pu-Vovf1nhtOpLKutX5gaW3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);